---
- name: Configure Firewall Only
  hosts: demogroup
  gather_facts: true
  become: true
  
  tasks:
    - name: Allow port 80 through the firewall
      firewalld:
       service: http
       permanent: yes
       state: enabled
      notify: Restart firewalld

  handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
