---
- name: Configure Firewall Only
  hosts: webservers,haproxy
  gather_facts: true
  become: true
  
  tasks:

    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
      notify: Restart firewalld

    - name: Allow port 80 through the firewall
      firewalld:
       service: http
       permanent: yes
       state: enabled
      notify: Restart firewalld

  handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
