---
- name: Install HAProxy Only
  hosts: haproxy
  gather_facts: true
  become: true
  
  tasks:
    - name: Install HAProxy - TASK
      yum:
        name: haproxy
        state: latest
      notify: Restart HAProxy - HANDLER

    - name: Source HAProxy cfg
      copy:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
  
  handlers:
    - name: Restart HAProxy - HANDLER
      service: 
        name: haproxy
        state: restarted