---
- name: Install HAProxy Only
  hosts: haproxy
  gather_facts: true
  become: true
  
  tasks:
    - name: Install HAProxy - TASK
      yum:
        name: haproxy
        state: latest
      notify: Restart HAProxy - HANDLER
  
  handlers:
    - name: Restart HAProxy - HANDLER
      service: 
        name: haproxy
        state: restarted