---
- name: Configure MOTD
  hosts: demogroup
  gather_facts: true
  become: true
  vars:
    my_motd_string: Is the default!
  
  tasks:
    - name: Template Custom MOTD
      template:
        src: templates/MOTD.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
