---
- name: Configure MOTD
  hosts: demogroup
  gather_facts: true
  become: true
  
  tasks:
    - name: Copy Custom MOTD
      copy:
        src: templates/testmotd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
