---
- name: Start Apache Only
  hosts: webservers
  gather_facts: true
  become: true
  
  tasks:
    - name: Starting HTTPD - TASK
      service:
        name: httpd
        state: started
        enabled: yes
